name: Build and Deploy
env:
  EM_VERSION: 1.39.18
  EM_CACHE_FOLDER: 'emsdk-cache'
on:
  push:
    branches: [ master ]
jobs:
  build-and-deploy:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup cache
        id: cache-system-libraries
        uses: actions/cache@v2
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}
      - uses: mymindstorm/setup-emsdk@v7
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      - name: Generate examples list
        run: scripts/genexamplestxt.sh > scripts/examples.txt
      - name: Build demo
        run: scripts/build_all_examples.sh ${{ env.GITHUB_SHA }}
      - name: Remove builder folder
        run: rm -rf objs/builder
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MESSAGE: ${{ env.GITHUB_SHA }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: objs # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
